<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>MaterialNumbers</AssemblyName>
    <RootNamespace>MaterialNumbers</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
    <OutputPath>bin/$(Configuration)/</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4871" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Runtime">
      <HintPath>$(RimWorldToolingRoot)/nuget-packages/microsoft.netframework.referenceassemblies.net472/1.0.3/build/.NETFramework/v4.7.2/Facades/System.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="CopyModAssembly" AfterTargets="Build">
    <MakeDir Directories="$(MSBuildProjectDirectory)/../../1.6/Assemblies" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(MSBuildProjectDirectory)/../../1.6/Assemblies" />
  </Target>

  <Target Name="RemoveDuplicateSystemRuntimeReference" BeforeTargets="ResolveAssemblyReferences">
    <ItemGroup>
      <Reference Remove="System.Runtime" />
    </ItemGroup>
  </Target>
</Project>
